# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Maurer's Personal Blog
email: andrew.b.maurer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  University of Georgia graduate student in mathematics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andrewmaurer.github.io" # the base hostname & protocol for your site
github_username:  andrewmaurer

# Build settings
markdown: kramdown
